### ISSUE TITLE
Phase-1-Scope-Lab

### ISSUE THREAD

**Issue by Baskakovs** [learn-co-curriculum/phase-1-scope-lab#6]
### Canvas Link

https://learning.flatironschool.com/courses/5300/assignments/179776?module_item_id=396969

### Concern

The second test of the lab seems to be wrong.

var customerName = 'bob'

function upperCaseCustomerName(){
   return customerName.toUpperCase()
}

Above, is my code. It seems to upper case the variable customerName on node, but still does not pass the test.

**Comment by lizbur10** [comment]
Hi @Baskakovs! This lab is asking you to do some things you wouldn't normally do as a way to better understand scope. The instructions for this function specify that it should **reset** the value of the `customerName` variable defined in the global scope. What your version is doing is just returning a value that is equal to the uppercase version of that variable.

If this is still unclear, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.
